### ISSUE TITLE
Problem running "filehistory" config example

### ISSUE THREAD

**Issue by chavvdarrr** [Fleex255/SprintDLL#1]
Hi, I tried the example script you had written for configuring FilHistory using SprintDLL
Any idea whats wrong?

SprintDLL.exe run file.sprint
CoCreateInstance returned 0
Function at 140721088124544 returned 0
Function at 140721088129184 returned 2147746564
Function at 140721088127584 returned 0
Function at 140721088128112 returned 0
Function at 140721088124848 returned 2147549183
FhServiceOpenPipe returned 0
FhServiceReloadConfiguration returned -2147220735
FhServiceClosePipe returned 0

**Comment by Fleex255** [comment]
The first function that's failing is [`ProvisionAndSetNewTarget`](https://msdn.microsoft.com/en-us/library/hh829818). The symbolic name for that error code as defined in [`FhErrors.h`](https://github.com/tpn/winddk-8.1/blob/master/Include/um/FhErrors.h) is `FHCFG_E_TARGET_NOT_CONNECTED`. I don't know for sure, but I suspect that means that the "network" location `\\localhost\FileHistory$\` is unavailable. Are you sure the share was created correctly?

**Comment by chavvdarrr** [comment]
10x, I just copied  the original from https://superuser.com/questions/1044050/configuring-windows-8-8-1-10-file-history-via-command-line/1289407#1289407 :/
Guess had to look first , sorry for the dumb question :)
