### ISSUE TITLE
Does not run on XP

### ISSUE THREAD

**Issue by spyrosmas** [Fleex255/SprintDLL#2]
SprintDLL.exe is not a valid Win32 application.
Can you compile with xp in mind? eg: Platform Toolset. v120_xp

**Comment by Fleex255** [comment]
I'm sorry, compiling for Windows XP is not possible because the last .NET version that runs on XP (4.0) does not support DefineDynamicAssembly.

**Comment by spyrosmas** [comment]
Autoit and VBA can call winapi functions decades ago. At least place a requirements line on your page about .net version and be prepared to change it "when needed".
