### ISSUE TITLE
Hi,

### ISSUE THREAD

**Issue by shoradrustum** [Fleex255/SprintDLL#4]
Hi, 

Can we do mapping of component with PagerDuty containers and services through API?
Also, any way to add PagerDuty services and service rules into it through API?

_Originally posted by @tyagian in https://www.merriam-webster.com/dictionary/verb

**Comment by Fleex255** [comment]
I'm afraid I'm not sure what you're referring to. SprintDLL is for calling native Windows API functions. It looks to me like PagerDuty has their own web API. If that web API is not what you need, please try looking for PagerDuty-specific automation options. Using their tools is likely to work much better than trying to work at the native DLL level.
